version: "3.7"
services:
  
  core:
    container_name: core
    build:
      context: ./services/core
    command: python3 main.py
    #environment:
    #- ES_USER=${ES_USER}
    #- ES_PASSWORD=${ES_PASSWORD}
    #- ES_SERVER=${ES_SERVER}
    volumes:
      - ./services/core:/code
    #ports:
    # # - 8000:8000
    